{% set name = "cdsutils" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 242ccd7ae5c29258d6ae374ec8950f77ee95a21fa42e420a6161c8d7a63a671a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cdsutils = cdsutils.__main__:main

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - setuptools-scm
  run:
    - ezca
    - gpstime
    - matplotlib-base
    - numpy
    - python >=3.5
    - python-nds2-client

test:
  requires:
    - pip
    - pytest
    - pytest-console-scripts
  imports:
    - cdsutils
  commands:
    - pip check
    - python -m pytest --pyargs cdsutils
    - cdsutils --help

about:
  home: https://git.ligo.org/cds/software/cdsutils/
  dev_url: https://git.ligo.org/cds/cdsutils/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING-GPL-3
  summary: Advanced LIGO CDS python utilities
  description: |
    Various python libraries and command line utilities for interacting
    with the Advanced LIGO control system.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
